### ISSUE TITLE
Youtube video not playing in video player

### ISSUE THREAD

**Issue by Dineshcg** [flutter-devs/flutter_video_player_demo#1]
**I am trying to play youtube video in plyer it not working, but other videos from network working fine.**

Error as below :
 com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 5091):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 5091):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5091):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 5091):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5091):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
E/ExoPlayerImplInternal( 5091):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal( 5091):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1024)
E/ExoPlayerImplInternal( 5091):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 5091):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 5091):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 5091):       at java.lang.Thread.run(Thread.java:923)

**Comment by CARocha** [comment]
not working video_player and chewie play youtube video if you need use https://pub.dev/packages/youtube_player_flutter

**Comment by iamrobusto** [comment]
lib/app/app.dart errors

line 76 :  tries to assign a TextSpan to a String
line 198: chewieController = chewieController!.copyWith(..) . chewieController has no such method.
